# Generated by Django 2.2.6 on 2019-10-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='nsme',
            new_name='name',
        ),
    ]
